"""Structured error codes for compliance-bundle verification failures.

v0.8 prep — drafted 2026-05-11. Pending Nel ratify + merge into generator.py
IdentityError raises. Integrators branch on .error_code instead of regexing
type(e).__name__ string.

Stability contract: codes are append-only. Renames forbidden post-v0.8 GA.
"""

from enum import Enum


class ErrorCode(str, Enum):
    # Shape / contract
    SHAPE_INVALID = "SHAPE_INVALID"
    EVENT_ID_DUPLICATE = "EVENT_ID_DUPLICATE"
    DECISION_ENUM_INVALID = "DECISION_ENUM_INVALID"
    POLICY_BUNDLE_HEX_INVALID = "POLICY_BUNDLE_HEX_INVALID"

    # Charset / DoS
    CHARSET_VIOLATION = "CHARSET_VIOLATION"
    LENGTH_CAP_EXCEEDED = "LENGTH_CAP_EXCEEDED"
    EVENT_COUNT_CAP_EXCEEDED = "EVENT_COUNT_CAP_EXCEEDED"

    # Timing
    TIMESTAMP_INVALID = "TIMESTAMP_INVALID"
    WINDOW_EXPIRED = "WINDOW_EXPIRED"

    # Identity / crypto
    OPERATOR_DID_TIER_MISMATCH = "OPERATOR_DID_TIER_MISMATCH"
    LINKAGE_MISMATCH = "LINKAGE_MISMATCH"
    SIGNATURE_INVALID = "SIGNATURE_INVALID"
    KEY_FORMAT_INVALID = "KEY_FORMAT_INVALID"
    OPERATOR_REGISTRY_LOOKUP_FAILED = "OPERATOR_REGISTRY_LOOKUP_FAILED"

    # Proof / canonicalization (per Nel lap-96 generator.py call-site audit)
    PROOF_MISSING = "PROOF_MISSING"
    PROOFVALUE_EMPTY = "PROOFVALUE_EMPTY"
    PROOFVALUE_TOO_LONG = "PROOFVALUE_TOO_LONG"
    PROOFVALUE_HEX_INVALID = "PROOFVALUE_HEX_INVALID"
    CANONICALIZATION_FAILED = "CANONICALIZATION_FAILED"

    # Substrate (general)
    SUBSTRATE_ATTESTATION_STALE = "SUBSTRATE_ATTESTATION_STALE"
    SUBSTRATE_ATTESTATION_INVALID = "SUBSTRATE_ATTESTATION_INVALID"

    # Substrate (lane-specific) — per Nel lap-111 substrate-pack call-site audit
    TPM_QUOTE_SIG_INVALID = "TPM_QUOTE_SIG_INVALID"
    TPM_PCR_MISMATCH = "TPM_PCR_MISMATCH"
    APPLE_SE_RP_ID_MISMATCH = "APPLE_SE_RP_ID_MISMATCH"
    APPLE_SE_COUNTER_REPLAY = "APPLE_SE_COUNTER_REPLAY"
    TEE_VENDOR_UNSUPPORTED = "TEE_VENDOR_UNSUPPORTED"
    TEE_REPORT_HASH_INVALID = "TEE_REPORT_HASH_INVALID"
    NONCE_REPLAY = "NONCE_REPLAY"
    HOST_FINGERPRINT_BINDING_DRIFT = "HOST_FINGERPRINT_BINDING_DRIFT"


__all__ = ["ErrorCode"]
